// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9u2nWt9NcQfQhqWtoATJ7yvSyZ6EtjsM',
    appId: '1:269425656719:web:b97cef880b6e0a86a7c1fa',
    messagingSenderId: '269425656719',
    projectId: 'dash-inside-knowledge-store',
    authDomain: 'dash-inside-knowledge-store.firebaseapp.com',
    storageBucket: 'dash-inside-knowledge-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzqqmMo7w0WBIIs-38MfoRt7wwBiBFGic',
    appId: '1:269425656719:android:a0ca4391177f6b5ea7c1fa',
    messagingSenderId: '269425656719',
    projectId: 'dash-inside-knowledge-store',
    storageBucket: 'dash-inside-knowledge-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCFEUFhMwUFzTMCNdUzlkIkEcku2LZuys',
    appId: '1:269425656719:ios:ce85c3701fcc96ffa7c1fa',
    messagingSenderId: '269425656719',
    projectId: 'dash-inside-knowledge-store',
    storageBucket: 'dash-inside-knowledge-store.appspot.com',
    iosClientId: '269425656719-3tp37co69jv8ppk3alfuf8bjvamjjbbi.apps.googleusercontent.com',
    iosBundleId: 'com.dashinside.knowledge',
  );
}
